CREATE TABLE ships (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  valid_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by VARCHAR(128) NOT NULL,
  context VARCHAR(128) NOT NULL,
  payload JSONB NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE shipyards (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  valid_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by VARCHAR(128) NOT NULL,
  context VARCHAR(128) NOT NULL,
  payload JSONB NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE jumpgates (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by VARCHAR(128) NOT NULL,
  context VARCHAR(128) NOT NULL,
  payload JSONB NOT NULL,
  PRIMARY KEY(id)
);
